{% set name = "jax" %}
{% set version = "0.4.7" %}

package:
  name: jax
  version: {{ version }}

source:
  # only pull source after PyPI release.
  url: https://pypi.io/packages/source/j/jax/jax-{{ version }}.tar.gz
  sha256: 5e7002d74db25f97c99b979d4ba1233b1ef26e1597e5fc468ad11d1c8a9dc4f8

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  string: {{ build_type }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}   #[build_type == 'cpu']
  string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }} #[build_type == 'cuda']

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - numpy {{ numpy }}
    - libopenblas {{ openblas }}
    - opt_einsum
    - scipy {{ scipy }}
    - ml_dtypes >=0.0.3
    - re2
    - c-ares
    - nccl {{ nccl }}          #[build_type == 'cuda']
    # Not declared in the metadata but essential to this package.
    # update minimum from https://github.com/google/jax/blob/main/jax/version.py#L21
    - jaxlib {{ version }}=cpu*    #[build_type == 'cpu']
    - jaxlib {{ version }}=cuda*   #[build_type == 'cuda']

test:
  imports:
    - jax
    - jax._src
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/jax
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Differentiate, compile, and transform Numpy code

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
